mysql:
  image: mysql:5.7
  ports:
  - "3306:3306"
  environment:
    MYSQL_DATABASE: forge
    MYSQL_ROOT_PASSWORD: password
redis:
  image: redis
  ports:
  - "6379:6379"
  command: redis-server --appendonly yes --requirepass foobared
  volumes:
  - redis-data:/data
